Try to workaround weird import cycles
This was causing weird duplicate types when depending on published
modules from other modules like:

```
error: TS2416 [ERROR]: Property 'toNumXY' in type 'NumXY' is not assignable to the same property in base type 'NumericalXY<number>'.
  Type '() => import("file:///home/stephen/dev/niedzielski/oidoid/ooz/src/2d/xy/num-xy.ts").NumXY' is not assignable to type '() => import("https://deno.land/x/ooz@v0.0.15/src/2d/xy/num-xy.ts").NumXY'.
    Type 'import("file:///home/stephen/dev/niedzielski/oidoid/ooz/src/2d/xy/num-xy.ts").NumXY' is not assignable to type 'import("https://deno.land/x/ooz@v0.0.15/src/2d/xy/num-xy.ts").NumXY'.
      Property '#x' in type 'NumXY' refers to a different member that cannot be accessed from within type 'NumXY'.
  toNumXY(): NumXY {
  ~~~~~~~
    at file:///home/stephen/dev/niedzielski/oidoid/ooz/src/2d/xy/num-xy.ts:234:3
make: *** [makefile:35: bundle] Error 1
```

https://github.com/denoland/deno/issues/11286